### ISSUE TITLE
[3.5.0-rc.6] Date Field w/ Time shows errors when clicking out of focus

### ISSUE THREAD

**Issue by neildaniels** [getkirby/kirby#2990]
**Describe the bug**  
The following Blueprint field works fine in Kirby 3.4.5.

```yaml
created:
  label: Published Date
  type: date
  translate: false
  time:
    step: 1
    notation: 12
  width: 1/3
```

In Kirby 3.5.0-rc.6, an error is shown after clicking outside the field.

**To Reproduce**  
1. Have above field
2. Create a new page, or open a page with an empty value
3. Click into the date field and pick "today"
4. The overlay hides
5. Click into **the time portion** of the field (seems to only happen when focusing into the time field)
6. Click outside to blur the focus

**Expected behavior**  
No error.

**Screenshots**  
<img width="369" alt="Screen Shot 2020-12-10 at 3 31 30 PM" src="https://user-images.githubusercontent.com/417182/101842475-f4e8d000-3afc-11eb-80ab-b89beea58322.png">
<img width="341" alt="Screen Shot 2020-12-10 at 3 31 35 PM" src="https://user-images.githubusercontent.com/417182/101842478-f6b29380-3afc-11eb-81a1-a297a1c50eca.png">
[Screen Recording 2020-12-10 at 3.27.25 PM.zip](https://github.com/getkirby/kirby/files/5676232/Screen.Recording.2020-12-10.at.3.27.25.PM.zip)

**Kirby Version**  
`3.5.0-rc.6`

**Console output**  
```
[Warning] TypeError: this[w.p(t)] is not a function. (In 'this[w.p(t)]()', 'this[w.p(t)]' is undefined) (app.js, line 1)
(anonymous function) — vendor.js:10398
toNearest — app.js:8515
toNearest
(anonymous function) — vendor.js:15061
(anonymous function) — vendor.js:15112
(anonymous function) — vendor.js:15216
onBlur — app.js:8465
onBlur
oe — vendor.js:14042
```

**Desktop (please complete the following information):**  
 - OS: macOS
 - Safari 14.0.1 (16610.2.11.51.8)
 - Chrome (87.0.4280.88)

**Comment by afbora** [comment]
![date-time-2](https://user-images.githubusercontent.com/3393422/101875649-07fead00-3b9c-11eb-9b7d-575d8728194f.gif)


While working on it, I noticed weird behaviors:

1. When we click on an empty place in the calendar or on the navigation, it deletes the date (I think the focus error appears after resolving)

2. There is a delay when we select the time and change the date from the calendar. You will notice that it first deletes the input and then refills it. Also this causes the savebar to disappear momentarily and come back again (when input empty). (Not seen in this video)

**Comment by distantnative** [comment]
@afbora those seem different problems, could you separate issues please? would help me a lot to not miss any of them :) thanks!

**Comment by distantnative** [comment]
@afbora your testing skills would be great here - for me it seems like https://github.com/getkirby/kirby/tree/fix/date-field solves this as well

**Comment by afbora** [comment]
@distantnative Yes, focus issue fixed with that branch 🎉

**Comment by distantnative** [comment]
Will be in the next RC and/or release.
